-- Supabase SQL schema for guestbook
-- 1) 테이블 생성
create table public.guestbook (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  created_at timestamptz not null default now()
);

-- 2) 공개 읽기/쓰기 정책 (익명 사용자를 위한 설정)
alter table public.guestbook enable row level security;

create policy "Allow public select on guestbook"
  on public.guestbook
  for select
  using (true);

create policy "Allow public insert on guestbook"
  on public.guestbook
  for insert
  with check (true);

-- 3) 필요한 경우 기본 데이터 추가
insert into public.guestbook (name, message)
values ('테스트', 'Supabase 방명록이 정상적으로 동작합니다.');
