-- Supabase SQL schema for guestbook and user accounts

-- 1) 방명록 테이블 생성
create table public.guestbook (
  id bigint generated by default as identity primary key,
  name text not null,
  password text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.guestbook enable row level security;

create policy "Allow public select on guestbook"
  on public.guestbook
  for select
  using (true);

create policy "Allow public insert on guestbook"
  on public.guestbook
  for insert
  with check (true);

create policy "Allow public delete on guestbook"
  on public.guestbook
  for delete
  using (true);

insert into public.guestbook (name, password, message)
values ('테스트', 'password123!', 'Supabase 방명록이 정상적으로 동작합니다.');

-- 2) 사용자 계정 테이블 생성
create table public.user_accounts (
  id bigint generated by default as identity primary key,
  username text not null unique,
  phone text not null,
  email text not null,
  password text not null,
  created_at timestamptz not null default now()
);

alter table public.user_accounts enable row level security;

create policy "Allow public select on user_accounts"
  on public.user_accounts
  for select
  using (true);

create policy "Allow public insert on user_accounts"
  on public.user_accounts
  for insert
  with check (true);
